# Site settings
title: apps.rymo.io
copyright:
    holder: Ryan Morrissey
    start: 2014
author: Ryan Morrissey
email: developer@apps.rymo.io
description: A place to store some live apps I've built.
baseurl: ""
url: "https://apps.rymo.io"
twitter_username: rymoio
github_username:  rymoio

# Build settings
markdown: kramdown
exclude: ["bower_components", "README.md", "config.codekit", "assets/less"]